GET http://localhost:1234/products
###
GET http://localhost:1234/users
###
GET http://localhost:1234/users/?name=JUAN

###
GET http://localhost:1234/products/?name=buzo
 
###
POST http://localhost:1234/products
Content-Type: application/json

{
    "name": "buzo",
    "brand": "nike",
    "category": 1,
    "price": 1000,
    "stock": 10,
    "description": "description",
    "sale": 20
}

###
DELETE http://localhost:1234/products/32



###
GET http://localhost:1234/categories

###
GET http://localhost:1234/promotions